/* ======================================================================
 * lights.h - Lights Out (a lamp-toggling puzzle) for CASTALIA/386
 * ----------------------------------------------------------------------
 * A 5x5 board of lamps.  Clicking one flips it AND its four neighbours;
 * put every lamp out to win.  Boards are generated by pressing random
 * lamps on a dark board, so every puzzle is solvable by construction.
 * ====================================================================== */
#ifndef LIGHTS_H
#define LIGHTS_H

#include "castalia.h"
#include "ui.h"

void   lights_open(void);
void   lights_draw(const Rect *client);
void   lights_click(const Rect *client, int mx, int my);
bool_t lights_key(int key);            /* N = new board; TRUE = repaint   */

#endif /* LIGHTS_H */
